import sympy as sy
from . import Multiple as Multiple
from ..abstracts import (
    AbstractKet as AbstractKet,
    Convertible as Convertible,
    Functional as Functional,
    HasRays as HasRays,
    Operable as Operable,
    Span as Span,
)
from ..geometries.spatials import Spatial as Spatial
from ..linalg.tensors import Tensor as Tensor
from ..precision import get_precision_config as get_precision_config
from ..utils.collections_ext import FrozenDict as FrozenDict
from ..utils.types_ext import full_typename as full_typename
from ..validations import need_validation as need_validation
from .state_space import (
    StateSpace as StateSpace,
    StateSpaceFactorization as StateSpaceFactorization,
)
from abc import ABC
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from typing import Any, Callable, Generic, TypeVar, overload
from typing_extensions import override

_IrrepType = TypeVar("_IrrepType")
_T = TypeVar("_T")

@dataclass(frozen=True)
class U1Basis(
    Spatial, Multiple[tuple[Any, ...]], AbstractKet[sy.Expr], HasRays, Convertible
):
    def __post_init__(self) -> None: ...
    @staticmethod
    def new(*rep: Any) -> U1Basis: ...
    @property
    def dim(self) -> int: ...
    def replace(self, irrep: Any) -> U1Basis: ...
    def irrep_of(self, T: type[_IrrepType]) -> _IrrepType: ...
    @override
    def ket(self, psi: U1Basis) -> sy.Expr: ...
    @override
    def rays(self) -> U1Basis: ...
    def __matmul__(self, other: U1Basis) -> U1Basis: ...
    @overload
    def __or__(self, other: U1Basis) -> U1Span: ...
    @overload
    def __or__(self, other: U1Span) -> U1Span: ...
    def __lt__(self, other: U1Basis) -> bool: ...
    def __gt__(self, other: U1Basis) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def repr_types(self) -> tuple[type, ...]: ...

@dataclass(frozen=True)
class U1Span(Span[U1Basis], Spatial, HasRays, Convertible):
    span: tuple["U1Basis", ...]
    @property
    def dim(self) -> int: ...
    def __iter__(self) -> Iterator["U1Basis"]: ...
    @override
    def elements(self) -> tuple["U1Basis", ...]: ...
    @override
    def rays(self) -> U1Span: ...
    @overload
    def __or__(self, other: U1Basis) -> U1Span: ...
    @overload
    def __or__(self, other: U1Span) -> U1Span: ...
    def __sub__(self, other: U1Span) -> U1Span: ...
    def __and__(self, other: U1Span) -> U1Span: ...
    def cross_gram(self, ket: U1Span) -> sy.ImmutableDenseMatrix: ...

@dataclass(frozen=True)
class HilbertSpace(HasRays, StateSpace[U1Basis], Span[U1Basis]):
    def __hash__(self) -> int: ...
    @staticmethod
    def new(itr: Iterable[U1Basis]) -> HilbertSpace: ...
    def __or__(self, other: U1Basis) -> HilbertSpace: ...  # type: ignore[override]
    def lookup(self, query: dict[type[Any], Any]) -> U1Basis: ...
    def group(
        self, **groups: Callable[[U1Basis], bool] | Any
    ) -> FrozenDict[str, "HilbertSpace"]: ...
    def group_by(self, *T: type) -> tuple["HilbertSpace", ...]: ...
    def is_homogeneous(self) -> bool: ...
    def canonical_basis_types(self) -> tuple[type[Any], ...]: ...
    def factorize(
        self, *irrep_types: tuple[type, ...], coef_on: int | None = None
    ) -> StateSpaceFactorization: ...
    @override
    def tensor_product(self, other: HilbertSpace) -> HilbertSpace: ...
    @override
    def rays(self) -> HilbertSpace: ...
    def cross_gram(self, another: HilbertSpace) -> Tensor: ...

def same_rays(a: HilbertSpace, b: HilbertSpace) -> bool: ...

class Opr(Functional, Operable, ABC):
    def invoke(self, obj: _T, **kwargs: Any) -> _T | Multiple[_T]: ...  # type: ignore[override]
    @overload
    def __matmul__(self, other: Opr) -> ComposedOpr: ...
    @overload
    def __matmul__(self, other: U1Basis) -> U1Basis: ...
    @overload
    def __matmul__(self, other: U1Span) -> U1Span: ...
    @overload
    def __matmul__(self, other: HilbertSpace) -> HilbertSpace: ...
    @overload
    def __matmul__(self, other: Multiple[_T]) -> Multiple[_T]: ...
    @overload
    def __matmul__(self, other: _T) -> _T | Multiple[_T]: ...

@dataclass(frozen=True)
class FuncOpr(Opr, Generic[_IrrepType]):
    T: type[_IrrepType]
    func: Callable[[_IrrepType], _IrrepType | Multiple[_IrrepType]]

@dataclass(frozen=True)
class ComposedOpr(Opr):
    ops: tuple[Opr, ...]
    def invoke(self, obj: _T, **kwargs: Any) -> _T | Multiple[_T]: ...  # type: ignore[override]
