from ..abstracts import Convertible as Convertible, Span as Span
from ..geometries.spatials import (
    Momentum as Momentum,
    ReciprocalLattice as ReciprocalLattice,
    Spatial as Spatial,
)
from ..validations import need_validation as need_validation
from collections import OrderedDict
from collections.abc import Iterator
from dataclasses import dataclass
from functools import lru_cache
from typing import Any, Callable, Generic, NamedTuple, Self, Sequence, TypeVar, overload
from typing_extensions import override

T = TypeVar("T")
StateSpaceType = TypeVar("StateSpaceType", bound="StateSpace[Any]")

@dataclass(frozen=True)
class StateSpace(Spatial, Convertible, Span[T], Generic[T]):
    structure: OrderedDict[T, int]
    @property
    def dim(self) -> int: ...
    @override
    def elements(self) -> tuple[T, ...]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
    def __hash__(self): ...
    @overload
    def __getitem__(self, v: int) -> T: ...
    @overload
    def __getitem__(self: Self, v: slice | range) -> Self: ...
    @overload
    def __getitem__(self: Self, v: Sequence[int]) -> Self: ...
    def __matmul__(self, other: Self) -> Self: ...
    def __add__(self, other: Self) -> Self: ...
    def __sub__(self, other: Self) -> Self: ...
    def __or__(self, other: Self) -> Self: ...
    def __and__(self, other: Self) -> Self: ...
    def __eq__(self, other: object) -> bool: ...
    def same_rays(self, other: StateSpace) -> bool: ...
    def map(self: Self, func: Callable[[T], T]) -> Self: ...
    def filter(self: Self, pred: Callable[[T], bool]) -> Self: ...
    def tensor_product(self, other: Self) -> Self: ...
    def extract(self, info_type: type[Any]) -> Any: ...

def restructure(structure: OrderedDict[T, int]) -> OrderedDict[T, int]: ...
@lru_cache
def permutation_order(src: StateSpace, dest: StateSpace) -> tuple[int, ...]: ...
@lru_cache
def embedding_order(sub: StateSpace, sup: StateSpace) -> tuple[int, ...]: ...
def same_rays(a: StateSpace, b: StateSpace) -> bool: ...
@dataclass(frozen=True)
class MomentumSpace(StateSpace[Momentum]):
    def __hash__(self) -> int: ...

@dataclass(frozen=True)
class BzPath:
    k_space: MomentumSpace
    labels: tuple
    waypoint_indices: tuple
    path_order: tuple
    path_positions: tuple

def momentum_to_momentumspace(k: Momentum) -> MomentumSpace: ...
@lru_cache
def brillouin_zone(lattice: ReciprocalLattice) -> MomentumSpace: ...
@dataclass(frozen=True)
class _BAxis: ...

@dataclass(frozen=True)
class BroadcastSpace(StateSpace[_BAxis]):
    structure: OrderedDict[_BAxis, int]
    def __hash__(self) -> int: ...

@dataclass(frozen=True)
class IndexSpace(StateSpace[int]):
    def __hash__(self) -> int: ...
    @staticmethod
    def linear(size: int) -> IndexSpace: ...

class StateSpaceFactorization(NamedTuple):
    factorized: tuple[StateSpace, ...]
    align_dim: StateSpace
