"""
Finite point groups generated by exact symbolic matrices.

This module defines [`FinitePointGroup`][qten.pointgroups.finite.FinitePointGroup],
the multi-generator counterpart to
[`PointGroupElement`][qten.pointgroups.elements.PointGroupElement]. A finite
point group stores exact generator matrices, closes under composition to obtain
all group elements, and optionally uses packaged Bilbao character tables to
build irrep projectors and polynomial sector bases.

Repository usage
----------------
Named crystallographic groups are usually constructed through
[`pointgroup()`][qten.pointgroups._pointgroups.pointgroup] or
[`named_pointgroup()`][qten.pointgroups._registry.named_pointgroup]. Use this
module directly when assembling a custom finite group from exact matrices.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from typing import Any, Iterable

import sympy as sy

from .elements import PointGroupElement
from .basis import PointGroupBasis


def _matrix_key(matrix: sy.ImmutableDenseMatrix) -> tuple[sy.Expr, ...]:
    return tuple(sy.simplify(entry) for entry in matrix)


def _character_expr(value: Any) -> sy.Expr:
    if isinstance(value, int):
        return sy.Integer(value)
    if isinstance(value, float):
        return sy.Rational(str(value))
    if isinstance(value, str):
        if value in ("", "·"):
            return sy.Integer(0)
        w = sy.exp(2 * sy.pi * sy.I / 3)
        text = value.replace("^", "**")
        return sy.simplify(sy.sympify(text, locals={"w": w}))
    return sy.sympify(value)


def _as_int(value: sy.Expr) -> int | None:
    simplified = sy.simplify(value)
    if simplified.is_integer:
        return int(simplified)
    return None


@dataclass(frozen=True)
class FinitePointGroup:
    r"""
    Finite point group represented by exact generator matrices.

    [`FinitePointGroup`][qten.pointgroups.finite.FinitePointGroup] stores one or
    more exact generators as
    [`PointGroupElement`][qten.pointgroups.elements.PointGroupElement] objects on
    a shared ordered axis tuple. Closing under composition yields the full group
    of linear actions. When packaged character-table data is attached through
    `irreps`, the group can project homogeneous polynomials onto irreducible
    sectors.

    Mathematical meaning
    --------------------
    Let \(G\) be the finite matrix group generated by the stored generators.
    The trivial projector on a representation \(D\) is
    \[
    P^{\mathrm{triv}} = \frac{1}{|G|}\sum_{g\in G} D(g).
    \]
    For an irrep \(\mu\) with characters \(\chi^\mu\) and dimension \(d_\mu\),
    \[
    P^\mu = \frac{d_\mu}{|G|}\sum_{g\in G}\chi^\mu(g)^* D(g).
    \]
    Here \(D(g)\) is the Euclidean polynomial representation of degree `order`
    induced by each generator matrix.

    Attributes
    ----------
    generators : tuple[PointGroupElement, ...]
        Exact linear generators that share the same ordered `axes`.
    axes : tuple[sy.Symbol, ...]
        Ordered coordinate symbols for every generator and group element.
    symbol : str | None
        Optional Hermann-Mauguin symbol, such as `"4mm"`.
    irreps : dict[str, Any] | None
        Optional packaged character-table payload with `class_labels`,
        `multiplicities`, and per-irrep character rows. Compared and hashed as
        identity metadata only.

    Notes
    -----
    Character-table labels are aligned to generated conjugacy classes by matrix
    invariants (order, determinant, trace, and common mirror geometry). Methods
    that need irrep data raise `ValueError` when `irreps` is absent or cannot be
    aligned to the generated group.
    """

    generators: tuple[PointGroupElement, ...]
    axes: tuple[sy.Symbol, ...]
    symbol: str | None = None
    irreps: dict[str, Any] | None = field(default=None, compare=False, hash=False)

    def __post_init__(self) -> None:
        if not self.generators:
            raise ValueError("FinitePointGroup requires at least one generator.")
        if any(generator.axes != self.axes for generator in self.generators):
            raise ValueError("All generators must share the group's ordered axes.")
        dim = len(self.axes)
        if any(generator.irrep.shape != (dim, dim) for generator in self.generators):
            raise ValueError("Generator matrix shape must match the axis dimension.")

    @classmethod
    def from_matrices(
        cls,
        matrices: Iterable[sy.ImmutableDenseMatrix],
        axes: tuple[sy.Symbol, ...],
        *,
        symbol: str | None = None,
        irreps: dict[str, Any] | None = None,
    ) -> "FinitePointGroup":
        """
        Build a finite point group from exact generator matrices.

        Parameters
        ----------
        matrices : Iterable[sy.ImmutableDenseMatrix]
            Generator matrices expressed on the ordered `axes` basis.
        axes : tuple[sy.Symbol, ...]
            Ordered coordinate symbols shared by every generator.
        symbol : str | None, optional
            Optional Hermann-Mauguin symbol for display and sector labels.
        irreps : dict[str, Any] | None, optional
            Optional packaged character-table payload.

        Returns
        -------
        FinitePointGroup
            Finite group whose generators are the corresponding
            [`PointGroupElement`][qten.pointgroups.elements.PointGroupElement]
            wrappers.
        """

        generators = tuple(
            PointGroupElement(irrep=matrix, axes=axes) for matrix in matrices
        )
        return cls(generators=generators, axes=axes, symbol=symbol, irreps=irreps)

    @lru_cache
    def elements(self, max_order: int = 512) -> tuple[PointGroupElement, ...]:
        """
        Generate all group elements by closure under the generators.

        Parameters
        ----------
        max_order : int, default 512
            Safety bound on the number of distinct elements discovered while
            closing the group.

        Returns
        -------
        tuple[PointGroupElement, ...]
            All distinct group elements, starting with the identity.

        Raises
        ------
        ValueError
            If closure exceeds `max_order`.
        """

        dim = len(self.axes)
        identity = PointGroupElement(
            irrep=sy.ImmutableDenseMatrix.eye(dim), axes=self.axes
        )
        elements = [identity]
        seen = {_matrix_key(identity.irrep)}
        frontier = [identity]

        while frontier:
            current = frontier.pop(0)
            for generator in self.generators:
                for candidate in (generator @ current, current @ generator):
                    key = _matrix_key(candidate.irrep)
                    if key in seen:
                        continue
                    seen.add(key)
                    elements.append(candidate)
                    frontier.append(candidate)
                    if len(elements) > max_order:
                        raise ValueError(
                            "Failed to close finite point group within "
                            f"max_order={max_order}."
                        )

        return tuple(elements)

    @property
    def order(self) -> int:
        """Number of generated group elements."""

        return len(self.elements())

    def is_abelian(self) -> bool:
        """Return whether all generated elements commute."""

        elements = self.elements()
        zero = sy.zeros(len(self.axes), len(self.axes))
        for i, left in enumerate(elements):
            for right in elements[i + 1 :]:
                if not sy.simplify(
                    left.irrep @ right.irrep - right.irrep @ left.irrep
                ).equals(zero):
                    return False
        return True

    @lru_cache
    def conjugacy_classes(self) -> tuple[tuple[int, ...], ...]:
        """
        Return conjugacy classes as tuples of element indices.

        Returns
        -------
        tuple[tuple[int, ...], ...]
            Each inner tuple lists indices into [`elements()`][qten.pointgroups.finite.FinitePointGroup.elements]
            that form one conjugacy class.
        """

        elements = self.elements()
        key_to_index = {
            _matrix_key(element.irrep): i for i, element in enumerate(elements)
        }
        unassigned = set(range(len(elements)))
        classes: list[tuple[int, ...]] = []
        while unassigned:
            i = min(unassigned)
            representative = elements[i]
            class_indices = set()
            for h in elements:
                conjugated = h @ representative @ h.inv()
                class_indices.add(key_to_index[_matrix_key(conjugated.irrep)])
            classes.append(tuple(sorted(class_indices)))
            unassigned -= class_indices
        return tuple(classes)

    def _reflection_label_2d(self, matrix: sy.ImmutableDenseMatrix) -> str:
        """Classify common 2D crystallographic mirror classes."""

        fixed = (matrix - sy.ImmutableDenseMatrix.eye(2)).nullspace()
        if not fixed:
            return "m"
        vec = fixed[0]
        x_nonzero = sy.simplify(vec[0]) != 0
        y_nonzero = sy.simplify(vec[1]) != 0
        if x_nonzero ^ y_nonzero:
            return "m100"
        return "m1-10"

    @staticmethod
    def _label_sense_matches(label: str, matrix: sy.ImmutableDenseMatrix) -> bool:
        """Match Bilbao's positive/negative rotation orientation suffix."""

        if label.endswith("^+"):
            expected_sign = 1
        elif label.endswith("^-"):
            expected_sign = -1
        else:
            return True

        rotation = -matrix if label.startswith("-") else matrix
        if rotation.rows < 2:
            return True
        sense = sy.simplify(rotation[1, 0] - rotation[0, 1])
        if sense.is_positive:
            return expected_sign == 1
        if sense.is_negative:
            return expected_sign == -1
        return True

    @staticmethod
    def _label_order(label: str) -> int | None:
        text = label.lstrip("-")
        for char in text:
            if char.isdigit():
                order = int(char)
                # A rotoinversion -n is inversion composed with an n-fold
                # rotation. For odd n its matrix order is therefore 2n;
                # for even n it remains n.
                if label.startswith("-") and order % 2:
                    return 2 * order
                return order
        return None

    def _label_matches_class(
        self,
        *,
        label: str,
        available_labels: tuple[str, ...],
        matrix: sy.ImmutableDenseMatrix,
        order: int,
        det: sy.Expr,
        trace: sy.Expr,
        dim: int,
    ) -> bool:
        """Return whether a class label is compatible with matrix invariants."""

        det_int = _as_int(det)
        trace_int = _as_int(trace)

        if label == "1":
            return order == 1
        if label == "-1":
            return order == 2 and det_int == -1 and trace_int == -dim
        if label.startswith("m"):
            if not (order == 2 and det_int == -1 and trace_int == dim - 2):
                return False
            if label in {"m100", "m1-10"} and {"m100", "m1-10"}.issubset(
                available_labels
            ):
                in_plane = matrix
                if dim == 3:
                    z_decoupled = all(
                        sy.simplify(matrix[i, 2]) == 0
                        and sy.simplify(matrix[2, i]) == 0
                        for i in range(2)
                    )
                    if not z_decoupled or sy.simplify(matrix[2, 2] - 1) != 0:
                        return True
                    in_plane = sy.ImmutableDenseMatrix(matrix[:2, :2])
                if in_plane.shape == (2, 2):
                    return self._reflection_label_2d(in_plane) == label
            return True
        if label.startswith("-"):
            label_order = self._label_order(label)
            if label_order is not None and order != label_order:
                return False
            if dim == 3:
                degree = next(
                    (int(char) for char in label.lstrip("-") if char.isdigit()),
                    None,
                )
                if degree is not None:
                    expected_trace = sy.simplify(-(1 + 2 * sy.cos(2 * sy.pi / degree)))
                    if sy.simplify(trace - expected_trace) != 0:
                        return False
            return det_int == -1 and self._label_sense_matches(label, matrix)
        label_order = self._label_order(label)
        if label_order is not None and order != label_order:
            return False
        return det_int == 1 and self._label_sense_matches(label, matrix)

    @lru_cache
    def _class_label_index_by_element(self) -> tuple[int, ...]:
        """Map each generated element index to irreps.class_labels index."""

        if not self.irreps:
            raise ValueError(f"No character-table data is available for {self.symbol}.")
        labels = tuple(self.irreps["class_labels"])
        multiplicities = tuple(int(m) for m in self.irreps["multiplicities"])
        classes = self.conjugacy_classes()
        elements = self.elements()
        if len(classes) != len(labels):
            raise ValueError(
                "Character-table class count does not match generated conjugacy classes "
                f"for point group {self.symbol}."
            )

        class_info: list[dict[str, Any]] = []
        for class_index, members in enumerate(classes):
            representative = elements[members[0]]
            matrix = sy.ImmutableDenseMatrix(sy.simplify(representative.irrep))
            class_info.append(
                {
                    "class_index": class_index,
                    "size": len(members),
                    "matrix": matrix,
                    "order": representative.group_order(),
                    "det": sy.simplify(matrix.det()),
                    "trace": sy.simplify(matrix.trace()),
                    "dim": matrix.rows,
                }
            )

        slot_candidates: dict[int, list[int]] = {}
        for info in class_info:
            size = info["size"]
            size_matches = [
                i
                for i, multiplicity in enumerate(multiplicities)
                if multiplicity == size
            ]
            if not size_matches:
                raise ValueError(
                    "Could not align generated conjugacy class sizes to character-table "
                    f"multiplicities for point group {self.symbol}."
                )
            strong_matches = [
                i
                for i in size_matches
                if self._label_matches_class(
                    label=labels[i],
                    available_labels=labels,
                    matrix=info["matrix"],
                    order=info["order"],
                    det=info["det"],
                    trace=info["trace"],
                    dim=info["dim"],
                )
            ]
            slot_candidates[info["class_index"]] = strong_matches or size_matches

        ordered_classes = sorted(
            slot_candidates, key=lambda idx: len(slot_candidates[idx])
        )
        assignment: dict[int, int] = {}
        used_slots: set[int] = set()

        def _search(pos: int) -> bool:
            if pos == len(ordered_classes):
                return True
            class_index = ordered_classes[pos]
            for slot_index in slot_candidates[class_index]:
                if slot_index in used_slots:
                    continue
                assignment[class_index] = slot_index
                used_slots.add(slot_index)
                if _search(pos + 1):
                    return True
                used_slots.remove(slot_index)
                del assignment[class_index]
            return False

        if not _search(0):
            raise ValueError(
                "Failed to align generated conjugacy classes with character-table labels "
                f"for point group {self.symbol}."
            )

        class_by_element = [0] * len(elements)
        for class_index, member_indices in enumerate(classes):
            slot_index = assignment[class_index]
            for element_index in member_indices:
                class_by_element[element_index] = slot_index
        return tuple(class_by_element)

    def element_class_indices(self) -> tuple[int, ...]:
        """
        Return the aligned character-table class index for each element.

        Returns
        -------
        tuple[int, ...]
            For each index into [`elements()`][qten.pointgroups.finite.FinitePointGroup.elements],
            the matching index into `irreps["class_labels"]`.

        Raises
        ------
        ValueError
            If character-table data is missing or cannot be aligned.
        """

        return self._class_label_index_by_element()

    def irrep_characters_by_element(self, irrep: str) -> tuple[sy.Expr, ...]:
        """
        Return irrep characters ordered by generated group elements.

        Parameters
        ----------
        irrep : str
            Irrep label from the packaged character table, such as `"A1"` or
            `"E"`.

        Returns
        -------
        tuple[sy.Expr, ...]
            Character values aligned to [`elements()`][qten.pointgroups.finite.FinitePointGroup.elements].

        Raises
        ------
        ValueError
            If the irrep is unknown or character-table data is incomplete.
        """

        if not self.irreps:
            raise ValueError(f"No character-table data is available for {self.symbol}.")
        irrep_table = self.irreps["irreps"]
        if irrep not in irrep_table:
            raise ValueError(f"Unknown irrep '{irrep}' for point group {self.symbol}.")

        labels = self.irreps["class_labels"]
        characters = tuple(
            _character_expr(character) for character in irrep_table[irrep]["characters"]
        )
        if len(characters) != len(labels):
            raise ValueError(
                f"Character row length for irrep '{irrep}' does not match class labels."
            )

        class_by_element = self._class_label_index_by_element()
        return tuple(characters[class_index] for class_index in class_by_element)

    @lru_cache
    def trivial_projector(self, order: int) -> sy.ImmutableDenseMatrix:
        r"""
        Project the polynomial representation onto the invariant sector.

        Parameters
        ----------
        order : int
            Homogeneous polynomial degree used for the Euclidean representation.

        Returns
        -------
        sy.ImmutableDenseMatrix
            Exact projector \(P^{\mathrm{triv}}\) onto group-invariant
            polynomials of degree `order`.
        """

        reps = [element.euclidean_repr(order) for element in self.elements()]
        projector = sy.zeros(reps[0].rows, reps[0].cols)
        for rep in reps:
            projector += rep
        return sy.ImmutableDenseMatrix(sy.simplify(projector / len(reps)))

    @lru_cache
    def irrep_projector(self, order: int, irrep: str) -> sy.ImmutableDenseMatrix:
        r"""
        Project the polynomial representation onto a character-table sector.

        Parameters
        ----------
        order : int
            Homogeneous polynomial degree used for the Euclidean representation.
        irrep : str
            Irrep label from the packaged character table.

        Returns
        -------
        sy.ImmutableDenseMatrix
            Exact projector
            \(P^\mu = \frac{d_\mu}{|G|}\sum_g \chi^\mu(g)^* D(g)\).

        Raises
        ------
        ValueError
            If the irrep is unknown or character-table data is incomplete.
        """

        if not self.irreps:
            raise ValueError(f"No character-table data is available for {self.symbol}.")
        irrep_table = self.irreps["irreps"]
        if irrep not in irrep_table:
            raise ValueError(f"Unknown irrep '{irrep}' for point group {self.symbol}.")

        labels = self.irreps["class_labels"]
        row = irrep_table[irrep]
        characters = tuple(
            _character_expr(character) for character in row["characters"]
        )
        if len(characters) != len(labels):
            raise ValueError(
                f"Character row length for irrep '{irrep}' does not match class labels."
            )

        elements = self.elements()
        class_by_element = self._class_label_index_by_element()
        reps = [element.euclidean_repr(order) for element in elements]
        projector = sy.zeros(reps[0].rows, reps[0].cols)
        for element_index, rep in enumerate(reps):
            class_index = class_by_element[element_index]
            projector += sy.conjugate(characters[class_index]) * rep

        dim = sy.Integer(row["dim"])
        return sy.ImmutableDenseMatrix(sy.simplify((dim / len(elements)) * projector))

    @lru_cache
    def irrep_basis(self, order: int, irrep: str) -> tuple[PointGroupBasis, ...]:
        """
        Return polynomial basis labels spanning a finite point-group irrep sector.

        Parameters
        ----------
        order : int
            Homogeneous polynomial degree for the Euclidean representation.
        irrep : str
            Irrep label from the packaged character table.

        Returns
        -------
        tuple[PointGroupBasis, ...]
            Normalized
            [`PointGroupBasis`][qten.pointgroups.basis.PointGroupBasis]
            labels spanning the image of the corresponding irrep projector.

        Raises
        ------
        ValueError
            If character-table data is missing.
        """

        if not self.irreps:
            raise ValueError(f"No character-table data is available for {self.symbol}.")
        irrep_data = self.irreps["irreps"][irrep]
        irrep_dim = int(irrep_data["dim"])
        projector = self.irrep_projector(order, irrep)
        euclidean_basis = self.generators[0].euclidean_basis(order)
        labels: list[PointGroupBasis] = []
        seen: set[tuple[sy.Expr, ...]] = set()
        for vec in projector.columnspace():
            rep = sy.ImmutableDenseMatrix(vec)
            if all(entry == 0 for entry in rep):
                continue
            basis = PointGroupBasis.from_rep(
                rep=rep,
                euclidean_basis=euclidean_basis,
                axes=self.axes,
                order=order,
                group=self.symbol or "<anonymous>",
                irrep=irrep,
                irrep_dim=irrep_dim,
                copy_index=len(labels) // max(irrep_dim, 1),
                component_index=len(labels) % max(irrep_dim, 1),
            )
            key = tuple(basis.rep)
            if key in seen:
                continue
            seen.add(key)
            labels.append(basis)
        return tuple(labels)

    @lru_cache
    def invariant_basis(self, order: int) -> tuple[PointGroupBasis, ...]:
        """
        Return invariant polynomial basis functions of the requested degree.

        Parameters
        ----------
        order : int
            Homogeneous polynomial degree for the Euclidean representation.

        Returns
        -------
        tuple[PointGroupBasis, ...]
            Normalized invariant
            [`PointGroupBasis`][qten.pointgroups.basis.PointGroupBasis]
            labels spanning the image of the trivial projector.
        """

        projector = self.trivial_projector(order)
        euclidean_basis = self.generators[0].euclidean_basis(order)
        labels: list[PointGroupBasis] = []
        seen: set[tuple[sy.Expr, ...]] = set()
        for vec in projector.columnspace():
            rep = sy.ImmutableDenseMatrix(vec)
            if all(entry == 0 for entry in rep):
                continue
            basis = PointGroupBasis.from_rep(
                rep=rep,
                euclidean_basis=euclidean_basis,
                axes=self.axes,
                order=order,
            )
            key = tuple(basis.rep)
            if key in seen:
                continue
            seen.add(key)
            labels.append(basis)
        return tuple(labels)
