"""
Finite point groups generated by exact symbolic matrices.

This module defines [`FinitePointGroup`][qten.pointgroups.finite.FinitePointGroup],
the multi-generator counterpart to
[`PointGroupElement`][qten.pointgroups.elements.PointGroupElement]. A finite
point group stores exact generator matrices, closes under composition to obtain
all group elements, and optionally uses packaged Bilbao character tables to
build irrep projectors and polynomial sector bases.

Repository usage
----------------
Named crystallographic groups are usually constructed through
[`pointgroup()`][qten.pointgroups._pointgroups.pointgroup] or
[`named_pointgroup()`][qten.pointgroups._registry.named_pointgroup]. Use this
module directly when assembling a custom finite group from exact matrices.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from typing import Any, Iterable

import sympy as sy

from .elements import PointGroupElement
from .basis import PointGroupBasis


def _matrix_key(matrix: sy.ImmutableDenseMatrix) -> tuple[float, ...]:
    """Identify a matrix by rounded numerical entries.

    Reoriented generators can have several exact sympy forms for the same
    rotation; a numeric key keeps group closure from treating them as new
    elements.
    """
    return tuple(round(complex(sy.N(entry, 20)).real, 8) for entry in matrix)


def _character_expr(value: Any) -> sy.Expr:
    if isinstance(value, int):
        return sy.Integer(value)
    if isinstance(value, float):
        return sy.Rational(str(value))
    if isinstance(value, (list, tuple)) and len(value) == 2:
        return sy.nsimplify(
            sy.Float(value[0]) + sy.I * sy.Float(value[1]), tolerance=1e-10
        )
    if isinstance(value, str):
        if value in ("", "·"):
            return sy.Integer(0)
        w = sy.exp(2 * sy.pi * sy.I / 3)
        text = value.replace("^", "**")
        return sy.simplify(sy.sympify(text, locals={"w": w}))
    return sy.sympify(value)


def _character_rows_close(
    left: list[complex], right: list[complex], *, atol: float = 1e-6
) -> bool:
    if len(left) != len(right):
        return False
    return all(
        abs(complex(first) - complex(second)) <= atol
        for first, second in zip(left, right)
    )


def _as_int(value: sy.Expr) -> int | None:
    simplified = sy.simplify(value)
    if simplified.is_integer:
        return int(simplified)
    return None


def _freeze_table(value: Any) -> Any:
    """Hashable snapshot of packaged irrep / spinor-irrep payloads."""
    if value is None:
        return None
    if isinstance(value, dict):
        return tuple(sorted((key, _freeze_table(item)) for key, item in value.items()))
    if isinstance(value, (list, tuple)):
        return tuple(_freeze_table(item) for item in value)
    if isinstance(value, sy.Matrix):
        return (value.rows, value.cols, tuple(sy.simplify(entry) for entry in value))
    return value


@dataclass(frozen=True)
class FinitePointGroup:
    r"""
    Finite point group represented by exact generator matrices.

    [`FinitePointGroup`][qten.pointgroups.finite.FinitePointGroup] stores one or
    more exact generators as
    [`PointGroupElement`][qten.pointgroups.elements.PointGroupElement] objects on
    a shared ordered axis tuple. Closing under composition yields the full group
    of linear actions. When packaged character-table data is attached through
    `irreps`, the group can project homogeneous polynomials onto irreducible
    sectors.

    Mathematical meaning
    --------------------
    Let \(G\) be the finite matrix group generated by the stored generators.
    The trivial projector on a representation \(D\) is
    \[
    P^{\mathrm{triv}} = \frac{1}{|G|}\sum_{g\in G} D(g).
    \]
    For an irrep \(\mu\) with characters \(\chi^\mu\) and dimension \(d_\mu\),
    \[
    P^\mu = \frac{d_\mu}{|G|}\sum_{g\in G}\chi^\mu(g)^* D(g).
    \]
    Here \(D(g)\) is the Euclidean polynomial representation of degree `order`
    induced by each generator matrix.

    Attributes
    ----------
    generators : tuple[PointGroupElement, ...]
        Exact linear generators that share the same ordered `axes`.
    axes : tuple[sy.Symbol, ...]
        Ordered coordinate symbols for every generator and group element.
    symbol : str | None
        Optional Hermann-Mauguin symbol, such as `"4mm"`.
    irreps : dict[str, Any] | None
        Optional packaged character-table payload with `class_labels`,
        `multiplicities`, and per-irrep character rows. Included in equality
        and hashing so table-dependent caches cannot collide.
    spinor_irreps : dict[str, Any] | None
        Optional class-wise projective spinor character data, same shape as
        `irreps`. Included in equality and hashing.
    spin : str
        Construction-time spin policy. ``"electron"`` (default) uses the
        SU(2) lift; ``"trivial"`` uses ``u(g)=I``.
    class_indices : tuple[int, ...] | None
        Optional map from generated element index to
        `irreps["class_labels"]` index. Set by
        [`reoriented_by`][qten.pointgroups.finite.FinitePointGroup.reoriented_by]
        so Bilbao characters follow conjugation. Included in equality and
        hashing so alignment-dependent caches cannot collide.

    Notes
    -----
    Character-table labels on a standard `xyz` group are aligned to generated
    conjugacy classes by matrix invariants (order, determinant, trace, and
    common mirror geometry). After a conjugation, the stored `class_indices`
    are used instead of re-matching geometry in the new frame. Ordinary and
    spinor tables are computed from the generated group when they are not
    packaged. Alignment raises `ValueError` when a packaged table cannot be
    matched to the generated conjugacy classes.
    """

    generators: tuple[PointGroupElement, ...]
    axes: tuple[sy.Symbol, ...]
    symbol: str | None = None
    irreps: dict[str, Any] | None = field(default=None, compare=False, hash=False)
    spinor_irreps: dict[str, Any] | None = field(
        default=None, compare=False, hash=False
    )
    spin: str = "electron"
    class_indices: tuple[int, ...] | None = field(
        default=None, compare=False, hash=False
    )

    def __post_init__(self) -> None:
        if not self.generators:
            raise ValueError("FinitePointGroup requires at least one generator.")
        if any(generator.axes != self.axes for generator in self.generators):
            raise ValueError("All generators must share the group's ordered axes.")
        dim = len(self.axes)
        if any(generator.irrep.shape != (dim, dim) for generator in self.generators):
            raise ValueError("Generator matrix shape must match the axis dimension.")
        if self.spin not in {"electron", "trivial"}:
            raise ValueError("spin must be 'electron' or 'trivial'.")
        if any(generator.spin != self.spin for generator in self.generators):
            raise ValueError("All generators must share the group's spin policy.")
        has_rotation3 = [
            generator.rotation3 is not None for generator in self.generators
        ]
        if any(has_rotation3) and not all(has_rotation3):
            raise ValueError(
                "All generators must store rotation3, or none of them. "
                "A missing rotation3 is not the identity."
            )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, FinitePointGroup):
            return NotImplemented
        return (
            self.generators == other.generators
            and self.axes == other.axes
            and self.symbol == other.symbol
            and self.irreps == other.irreps
            and self.spinor_irreps == other.spinor_irreps
            and self.spin == other.spin
            and self.class_indices == other.class_indices
        )

    def __hash__(self) -> int:
        return hash(
            (
                self.generators,
                self.axes,
                self.symbol,
                _freeze_table(self.irreps),
                _freeze_table(self.spinor_irreps),
                self.spin,
                self.class_indices,
            )
        )

    @classmethod
    def from_matrices(
        cls,
        matrices: Iterable[sy.ImmutableDenseMatrix],
        axes: tuple[sy.Symbol, ...],
        *,
        symbol: str | None = None,
        irreps: dict[str, Any] | None = None,
        spinor_irreps: dict[str, Any] | None = None,
        rotation3s: Iterable[sy.ImmutableDenseMatrix | None] | None = None,
        spin: str = "electron",
        class_indices: tuple[int, ...] | None = None,
    ) -> "FinitePointGroup":
        """
        Build a finite point group from exact generator matrices.

        Parameters
        ----------
        matrices : Iterable[sy.ImmutableDenseMatrix]
            Generator matrices expressed on the ordered `axes` basis.
        axes : tuple[sy.Symbol, ...]
            Ordered coordinate symbols shared by every generator.
        symbol : str | None, optional
            Optional Hermann-Mauguin symbol for display and sector labels.
        irreps : dict[str, Any] | None, optional
            Optional packaged character-table payload.
        spinor_irreps : dict[str, Any] | None, optional
            Optional class-wise projective spinor character data.
        rotation3s : Iterable[sy.ImmutableDenseMatrix | None] | None, optional
            Optional Cartesian O(3) matrix for each generator, used when the
            spatial matrices are not already 3D.
        spin : str, optional
            Construction-time spin policy.
        class_indices : tuple[int, ...] | None, optional
            Optional generated-element to character-table class map.

        Returns
        -------
        FinitePointGroup
            Finite group whose generators are the corresponding
            [`PointGroupElement`][qten.pointgroups.elements.PointGroupElement]
            wrappers.
        """

        matrix_list = tuple(matrices)
        if rotation3s is None:
            if len(axes) == 3:
                rotation_list = matrix_list
            else:
                rotation_list = (None,) * len(matrix_list)
        else:
            rotation_list = tuple(rotation3s)
            if len(rotation_list) != len(matrix_list):
                raise ValueError("rotation3s must contain one matrix per generator.")
        if spin not in {"electron", "trivial"}:
            raise ValueError("spin must be 'electron' or 'trivial'.")
        generators = tuple(
            PointGroupElement(irrep=matrix, axes=axes, rotation3=rotation3, spin=spin)
            for matrix, rotation3 in zip(matrix_list, rotation_list)
        )
        return cls(
            generators=generators,
            axes=axes,
            symbol=symbol,
            irreps=irreps,
            spinor_irreps=spinor_irreps,
            spin=spin,
            class_indices=class_indices,
        )

    @lru_cache
    def elements(self, max_order: int = 512) -> tuple[PointGroupElement, ...]:
        """
        Generate all group elements by closure under the generators.

        Parameters
        ----------
        max_order : int, default 512
            Safety bound on the number of distinct elements discovered while
            closing the group.

        Returns
        -------
        tuple[PointGroupElement, ...]
            All distinct group elements, starting with the identity.

        Raises
        ------
        ValueError
            If closure exceeds `max_order`.
        """

        dim = len(self.axes)
        rotation3 = None
        if any(generator.rotation3 is not None for generator in self.generators):
            rotation3 = sy.ImmutableDenseMatrix.eye(3)
        identity = PointGroupElement(
            irrep=sy.ImmutableDenseMatrix.eye(dim),
            axes=self.axes,
            rotation3=rotation3,
            spin=self.spin,
        )
        elements = [identity]
        seen = {_matrix_key(identity.irrep)}
        frontier = [identity]

        while frontier:
            current = frontier.pop(0)
            for generator in self.generators:
                for candidate in (generator @ current, current @ generator):
                    key = _matrix_key(candidate.irrep)
                    if key in seen:
                        continue
                    seen.add(key)
                    elements.append(candidate)
                    frontier.append(candidate)
                    if len(elements) > max_order:
                        raise ValueError(
                            "Failed to close finite point group within "
                            f"max_order={max_order}."
                        )

        return tuple(elements)

    @property
    def order(self) -> int:
        """Number of generated group elements."""

        return len(self.elements())

    def is_abelian(self) -> bool:
        """Return whether all generated elements commute."""

        elements = self.elements()
        zero = sy.zeros(len(self.axes), len(self.axes))
        for i, left in enumerate(elements):
            for right in elements[i + 1 :]:
                if not sy.simplify(
                    left.irrep @ right.irrep - right.irrep @ left.irrep
                ).equals(zero):
                    return False
        return True

    @lru_cache
    def conjugacy_classes(self) -> tuple[tuple[int, ...], ...]:
        """
        Return conjugacy classes as tuples of element indices.

        Returns
        -------
        tuple[tuple[int, ...], ...]
            Each inner tuple lists indices into [`elements()`][qten.pointgroups.finite.FinitePointGroup.elements]
            that form one conjugacy class.
        """

        elements = self.elements()
        key_to_index = {
            _matrix_key(element.irrep): i for i, element in enumerate(elements)
        }
        unassigned = set(range(len(elements)))
        classes: list[tuple[int, ...]] = []
        while unassigned:
            i = min(unassigned)
            representative = elements[i]
            class_indices = set()
            for h in elements:
                conjugated = h @ representative @ h.inv()
                class_indices.add(key_to_index[_matrix_key(conjugated.irrep)])
            classes.append(tuple(sorted(class_indices)))
            unassigned -= class_indices
        return tuple(classes)

    def _reflection_label_2d(self, matrix: sy.ImmutableDenseMatrix) -> str:
        """Classify common 2D crystallographic mirror classes."""

        fixed = (matrix - sy.ImmutableDenseMatrix.eye(2)).nullspace()
        if not fixed:
            return "m"
        vec = fixed[0]
        x_nonzero = sy.simplify(vec[0]) != 0
        y_nonzero = sy.simplify(vec[1]) != 0
        if x_nonzero ^ y_nonzero:
            return "m100"
        return "m1-10"

    @staticmethod
    def _label_sense_matches(label: str, matrix: sy.ImmutableDenseMatrix) -> bool:
        """Match Bilbao's positive/negative rotation orientation suffix."""

        if label.endswith("^+"):
            expected_sign = 1
        elif label.endswith("^-"):
            expected_sign = -1
        else:
            return True

        rotation = -matrix if label.startswith("-") else matrix
        if rotation.rows < 2:
            return True
        sense = sy.simplify(rotation[1, 0] - rotation[0, 1])
        if sense.is_positive:
            return expected_sign == 1
        if sense.is_negative:
            return expected_sign == -1
        return True

    @staticmethod
    def _label_order(label: str) -> int | None:
        text = label.lstrip("-")
        for char in text:
            if char.isdigit():
                order = int(char)
                # A rotoinversion -n is inversion composed with an n-fold
                # rotation. For odd n its matrix order is therefore 2n;
                # for even n it remains n.
                if label.startswith("-") and order % 2:
                    return 2 * order
                return order
        return None

    def _label_matches_class(
        self,
        *,
        label: str,
        available_labels: tuple[str, ...],
        matrix: sy.ImmutableDenseMatrix,
        order: int,
        det: sy.Expr,
        trace: sy.Expr,
        dim: int,
    ) -> bool:
        """Return whether a class label is compatible with matrix invariants."""

        det_int = _as_int(det)
        trace_int = _as_int(trace)

        if label == "1":
            return order == 1
        if label == "-1":
            return order == 2 and det_int == -1 and trace_int == -dim
        if label.startswith("m"):
            if not (order == 2 and det_int == -1 and trace_int == dim - 2):
                return False
            if label in {"m100", "m1-10"} and {"m100", "m1-10"}.issubset(
                available_labels
            ):
                in_plane = matrix
                if dim == 3:
                    z_decoupled = all(
                        sy.simplify(matrix[i, 2]) == 0
                        and sy.simplify(matrix[2, i]) == 0
                        for i in range(2)
                    )
                    if not z_decoupled or sy.simplify(matrix[2, 2] - 1) != 0:
                        return True
                    in_plane = sy.ImmutableDenseMatrix(matrix[:2, :2])
                if in_plane.shape == (2, 2):
                    return self._reflection_label_2d(in_plane) == label
            return True
        if label.startswith("-"):
            label_order = self._label_order(label)
            if label_order is not None and order != label_order:
                return False
            if dim == 3:
                degree = next(
                    (int(char) for char in label.lstrip("-") if char.isdigit()),
                    None,
                )
                if degree is not None:
                    expected_trace = sy.simplify(-(1 + 2 * sy.cos(2 * sy.pi / degree)))
                    if sy.simplify(trace - expected_trace) != 0:
                        return False
            return det_int == -1 and self._label_sense_matches(label, matrix)
        label_order = self._label_order(label)
        if label_order is not None and order != label_order:
            return False
        return det_int == 1 and self._label_sense_matches(label, matrix)

    def _generated_class_indices(self) -> tuple[int, ...]:
        """Map each element to its generated conjugacy-class index."""
        class_by_element = [0] * self.order
        for class_index, members in enumerate(self.conjugacy_classes()):
            for element_index in members:
                class_by_element[element_index] = class_index
        return tuple(class_by_element)

    @lru_cache
    def ordinary_table(self) -> dict[str, Any]:
        """Return ordinary irreps, computing them when no table is packaged."""
        if self.irreps:
            return self.irreps
        from ._characters import compute_ordinary_irreps

        return compute_ordinary_irreps(self)

    @lru_cache
    def _class_label_index_by_element(self) -> tuple[int, ...]:
        """Map each generated element index to irreps.class_labels index."""

        if self.class_indices is not None:
            if len(self.class_indices) != self.order:
                raise ValueError(
                    "Stored class_indices length does not match the generated "
                    f"group order for point group {self.symbol}."
                )
            return self.class_indices
        table = self.ordinary_table()
        if table.get("source") == "qten-computed":
            return self._generated_class_indices()
        if not self.irreps:
            raise ValueError(f"No character-table data is available for {self.symbol}.")
        labels = tuple(self.irreps["class_labels"])
        multiplicities = tuple(int(m) for m in self.irreps["multiplicities"])
        classes = self.conjugacy_classes()
        elements = self.elements()
        if len(classes) != len(labels):
            raise ValueError(
                "Character-table class count does not match generated conjugacy classes "
                f"for point group {self.symbol}."
            )

        class_info: list[dict[str, Any]] = []
        for class_index, members in enumerate(classes):
            representative = elements[members[0]]
            matrix = sy.ImmutableDenseMatrix(sy.simplify(representative.irrep))
            class_info.append(
                {
                    "class_index": class_index,
                    "size": len(members),
                    "matrix": matrix,
                    "order": representative.group_order(),
                    "det": sy.simplify(matrix.det()),
                    "trace": sy.simplify(matrix.trace()),
                    "dim": matrix.rows,
                }
            )

        slot_candidates: dict[int, list[int]] = {}
        for info in class_info:
            size = info["size"]
            size_matches = [
                i
                for i, multiplicity in enumerate(multiplicities)
                if multiplicity == size
            ]
            if not size_matches:
                raise ValueError(
                    "Could not align generated conjugacy class sizes to character-table "
                    f"multiplicities for point group {self.symbol}."
                )
            strong_matches = [
                i
                for i in size_matches
                if self._label_matches_class(
                    label=labels[i],
                    available_labels=labels,
                    matrix=info["matrix"],
                    order=info["order"],
                    det=info["det"],
                    trace=info["trace"],
                    dim=info["dim"],
                )
            ]
            if not strong_matches:
                raise ValueError(
                    "Could not geometrically align conjugacy class "
                    f"(size={info['size']}, order={info['order']}, det={info['det']}, "
                    f"trace={info['trace']}) to character-table labels "
                    f"for point group {self.symbol}."
                )
            slot_candidates[info["class_index"]] = strong_matches

        ordered_classes = sorted(
            slot_candidates, key=lambda idx: len(slot_candidates[idx])
        )
        assignment: dict[int, int] = {}
        used_slots: set[int] = set()

        def _search(pos: int) -> bool:
            if pos == len(ordered_classes):
                return True
            class_index = ordered_classes[pos]
            for slot_index in slot_candidates[class_index]:
                if slot_index in used_slots:
                    continue
                assignment[class_index] = slot_index
                used_slots.add(slot_index)
                if _search(pos + 1):
                    return True
                used_slots.remove(slot_index)
                del assignment[class_index]
            return False

        if not _search(0):
            raise ValueError(
                "Failed to align generated conjugacy classes with character-table labels "
                f"for point group {self.symbol}."
            )

        class_by_element = [0] * len(elements)
        for class_index, member_indices in enumerate(classes):
            slot_index = assignment[class_index]
            for element_index in member_indices:
                class_by_element[element_index] = slot_index
        return tuple(class_by_element)

    def element_class_indices(self) -> tuple[int, ...]:
        """
        Return the aligned character-table class index for each element.

        Returns
        -------
        tuple[int, ...]
            For each index into [`elements()`][qten.pointgroups.finite.FinitePointGroup.elements],
            the matching index into `irreps["class_labels"]`.

        Raises
        ------
        ValueError
            If character-table data is missing or cannot be aligned.
        """

        return self._class_label_index_by_element()

    def irrep_characters_by_element(self, irrep: str) -> tuple[sy.Expr, ...]:
        """
        Return irrep characters ordered by generated group elements.

        Parameters
        ----------
        irrep : str
            Irrep label from the packaged character table, such as `"A1"` or
            `"E"`.

        Returns
        -------
        tuple[sy.Expr, ...]
            Character values aligned to [`elements()`][qten.pointgroups.finite.FinitePointGroup.elements].

        Raises
        ------
        ValueError
            If the irrep is unknown or character-table data is incomplete.
        """

        table = self.ordinary_table()
        irrep_table = table["irreps"]
        if irrep not in irrep_table:
            raise ValueError(f"Unknown irrep '{irrep}' for point group {self.symbol}.")

        labels = table["class_labels"]
        characters = tuple(
            _character_expr(character) for character in irrep_table[irrep]["characters"]
        )
        if len(characters) != len(labels):
            raise ValueError(
                f"Character row length for irrep '{irrep}' does not match class labels."
            )

        class_by_element = self._class_label_index_by_element()
        return tuple(characters[class_index] for class_index in class_by_element)

    @lru_cache
    def spinor_table(self) -> dict[str, Any]:
        """Return class-wise spinor data, computing it from the SU(2) lift if needed."""
        if self.spin != "electron":
            raise ValueError(
                f"Point group {self.symbol} was defined with spin={self.spin!r}."
            )
        if self.spinor_irreps:
            return self.spinor_irreps
        from ._characters import compute_spinor_irreps

        return compute_spinor_irreps(self)

    def spinor_irrep_characters_by_element(self, irrep: str) -> tuple[complex, ...]:
        """Return projective spinor characters in generated-element order.

        Class-wise spinor rows zero non-ω-regular classes. Projectors use the
        hat-table section on each generated element instead.
        """
        table = self.spinor_table()
        if not table:
            raise ValueError(
                f"No spinor character-table data is available for {self.symbol}."
            )
        irrep_table = table["irreps"]
        if irrep not in irrep_table:
            raise ValueError(
                f"Unknown spinor irrep '{irrep}' for point group {self.symbol}."
            )
        labels = table.get("class_labels")
        if not labels:
            raise ValueError(f"Spinor table for {self.symbol} is missing class labels.")
        if self.irreps and labels != list(self.irreps["class_labels"]):
            raise ValueError(
                "Spinor class labels must match the ordinary class labels "
                f"for {self.symbol}."
            )
        characters = self._spinor_element_characters()[irrep]
        if len(characters) != self.order:
            raise ValueError(
                f"Spinor characters for '{irrep}' do not match the group order."
            )
        return characters

    @lru_cache
    def _spinor_element_characters(self) -> dict[str, tuple[complex, ...]]:
        """Element-wise spinor χ, computed live when the packaged table omits it."""
        from ._characters import compute_spinor_irreps, parse_class_character

        table = self.spinor_table()
        irrep_table = table["irreps"]
        if all(
            row.get("characters_by_element") is not None for row in irrep_table.values()
        ):
            return {
                name: tuple(
                    parse_class_character(value)
                    for value in row["characters_by_element"]
                )
                for name, row in irrep_table.items()
            }

        live = compute_spinor_irreps(self)
        live_irreps = live["irreps"]
        result: dict[str, tuple[complex, ...]] = {}
        for name, packaged in irrep_table.items():
            packaged_class = [
                parse_class_character(value) for value in packaged["characters"]
            ]
            matches = [
                row
                for row in live_irreps.values()
                if _character_rows_close(
                    packaged_class,
                    [parse_class_character(value) for value in row["characters"]],
                )
            ]
            if len(matches) == 1:
                encoded = matches[0]["characters_by_element"]
            elif name in live_irreps:
                # Identical class-wise rows (e.g. 3m spinor_1 / spinor_2)
                # cannot be matched by class averages.
                encoded = live_irreps[name]["characters_by_element"]
            else:
                raise ValueError(
                    "Cannot recover element-wise spinor characters for "
                    f"'{name}' in {self.symbol}."
                )
            result[name] = tuple(parse_class_character(value) for value in encoded)
        return result

    def reoriented_by(self, rotation: sy.Matrix) -> "FinitePointGroup":
        r"""
        Return the same abstract group with every matrix conjugated by `rotation`.

        Ordinary characters are class functions: each conjugated element keeps
        the Bilbao class index of its preimage. Spinor characters are
        recomputed from the reoriented SU(2) lifts.
        """
        matrix = sy.ImmutableDenseMatrix(sy.simplify(rotation))
        dim = len(self.axes)
        if matrix.shape != (dim, dim):
            raise ValueError(
                f"Reorientation matrix must be {dim}x{dim}, got {matrix.shape}."
            )
        inverse = sy.ImmutableDenseMatrix(sy.simplify(matrix.inv()))

        def _reoriented_rotation3(
            generator: PointGroupElement,
        ) -> sy.ImmutableDenseMatrix | None:
            if generator.rotation3 is None:
                return None
            if dim == 3:
                return sy.ImmutableDenseMatrix(
                    sy.simplify(matrix @ generator.rotation3 @ inverse)
                )
            from ..phys.spin import _embed_in_cartesian_xyz

            axis_names = tuple(getattr(axis, "name", str(axis)) for axis in self.axes)
            embedded = _embed_in_cartesian_xyz(matrix, axis_names)
            embedded_inv = _embed_in_cartesian_xyz(inverse, axis_names)
            return sy.ImmutableDenseMatrix(
                sy.simplify(embedded @ generator.rotation3 @ embedded_inv)
            )

        new_generators = tuple(
            PointGroupElement(
                irrep=sy.ImmutableDenseMatrix(
                    sy.simplify(matrix @ generator.irrep @ inverse)
                ),
                axes=self.axes,
                rotation3=_reoriented_rotation3(generator),
                spin=self.spin,
            )
            for generator in self.generators
        )
        reoriented = FinitePointGroup(
            generators=new_generators,
            axes=self.axes,
            symbol=self.symbol,
            irreps=self.irreps,
            spinor_irreps=None,
            spin=self.spin,
        )
        transported = self._transported_class_indices(reoriented, matrix, inverse)
        if transported is None:
            return reoriented
        return FinitePointGroup(
            generators=reoriented.generators,
            axes=reoriented.axes,
            symbol=reoriented.symbol,
            irreps=reoriented.irreps,
            spinor_irreps=None,
            spin=reoriented.spin,
            class_indices=transported,
        )

    def _transported_class_indices(
        self,
        reoriented: "FinitePointGroup",
        rotation: sy.ImmutableDenseMatrix,
        inverse: sy.ImmutableDenseMatrix,
    ) -> tuple[int, ...] | None:
        """Copy Bilbao class indices through ``g' = Q g Q^{-1}``."""
        if not self.irreps:
            return None
        old_key_to_class = {
            _matrix_key(element.irrep): class_index
            for element, class_index in zip(
                self.elements(), self._class_label_index_by_element()
            )
        }
        transported: list[int] = []
        for element in reoriented.elements():
            preimage = sy.ImmutableDenseMatrix(
                sy.simplify(inverse @ element.irrep @ rotation)
            )
            key = _matrix_key(preimage)
            if key not in old_key_to_class:
                raise ValueError(
                    "Reorientation did not preserve the generated group: "
                    f"could not recover the preimage of an element of {self.symbol}."
                )
            transported.append(old_key_to_class[key])
        return tuple(transported)

    @lru_cache
    def trivial_projector(self, order: int) -> sy.ImmutableDenseMatrix:
        r"""
        Project the polynomial representation onto the invariant sector.

        Parameters
        ----------
        order : int
            Homogeneous polynomial degree used for the Euclidean representation.

        Returns
        -------
        sy.ImmutableDenseMatrix
            Exact projector \(P^{\mathrm{triv}}\) onto group-invariant
            polynomials of degree `order`.
        """

        reps = [element.euclidean_repr(order) for element in self.elements()]
        projector = sy.zeros(reps[0].rows, reps[0].cols)
        for rep in reps:
            projector += rep
        return sy.ImmutableDenseMatrix(sy.simplify(projector / len(reps)))

    @lru_cache
    def irrep_projector(self, order: int, irrep: str) -> sy.ImmutableDenseMatrix:
        r"""
        Project the polynomial representation onto a character-table sector.

        Parameters
        ----------
        order : int
            Homogeneous polynomial degree used for the Euclidean representation.
        irrep : str
            Irrep label from the packaged or computed character table.

        Returns
        -------
        sy.ImmutableDenseMatrix
            Exact projector
            \(P^\mu = \frac{d_\mu}{|G|}\sum_g \chi^\mu(g)^* D(g)\).

        Raises
        ------
        ValueError
            If the irrep is unknown or character-table data is incomplete.
        """

        table = self.ordinary_table()
        irrep_table = table["irreps"]
        if irrep not in irrep_table:
            raise ValueError(f"Unknown irrep '{irrep}' for point group {self.symbol}.")

        labels = table["class_labels"]
        row = irrep_table[irrep]
        characters = tuple(
            _character_expr(character) for character in row["characters"]
        )
        if len(characters) != len(labels):
            raise ValueError(
                f"Character row length for irrep '{irrep}' does not match class labels."
            )

        elements = self.elements()
        class_by_element = self._class_label_index_by_element()
        reps = [element.euclidean_repr(order) for element in elements]
        projector = sy.zeros(reps[0].rows, reps[0].cols)
        for element_index, rep in enumerate(reps):
            class_index = class_by_element[element_index]
            projector += sy.conjugate(characters[class_index]) * rep

        dim = sy.Integer(row["dim"])
        return sy.ImmutableDenseMatrix(sy.simplify((dim / len(elements)) * projector))

    @lru_cache
    def irrep_basis(self, order: int, irrep: str) -> tuple[PointGroupBasis, ...]:
        """
        Return polynomial basis labels spanning a finite point-group irrep sector.

        Parameters
        ----------
        order : int
            Homogeneous polynomial degree for the Euclidean representation.
        irrep : str
            Irrep label from the packaged or computed character table.

        Returns
        -------
        tuple[PointGroupBasis, ...]
            Normalized
            [`PointGroupBasis`][qten.pointgroups.basis.PointGroupBasis]
            labels spanning the image of the corresponding irrep projector.

        Raises
        ------
        ValueError
            If the irrep is unknown or character-table data is incomplete.
        """

        table = self.ordinary_table()
        if irrep not in table["irreps"]:
            raise ValueError(f"Unknown irrep '{irrep}' for point group {self.symbol}.")
        irrep_data = table["irreps"][irrep]
        irrep_dim = int(irrep_data["dim"])
        projector = self.irrep_projector(order, irrep)
        euclidean_basis = self.generators[0].euclidean_basis(order)
        labels: list[PointGroupBasis] = []
        seen: set[tuple[sy.Expr, ...]] = set()
        for vec in projector.columnspace():
            rep = sy.ImmutableDenseMatrix(vec)
            if all(entry == 0 for entry in rep):
                continue
            basis = PointGroupBasis.from_rep(
                rep=rep,
                euclidean_basis=euclidean_basis,
                axes=self.axes,
                order=order,
                group=self.symbol or "<anonymous>",
                irrep=irrep,
                irrep_dim=irrep_dim,
                copy_index=len(labels) // max(irrep_dim, 1),
                component_index=len(labels) % max(irrep_dim, 1),
            )
            key = tuple(basis.rep)
            if key in seen:
                continue
            seen.add(key)
            labels.append(basis)
        return tuple(labels)

    @lru_cache
    def invariant_basis(self, order: int) -> tuple[PointGroupBasis, ...]:
        """
        Return invariant polynomial basis functions of the requested degree.

        Parameters
        ----------
        order : int
            Homogeneous polynomial degree for the Euclidean representation.

        Returns
        -------
        tuple[PointGroupBasis, ...]
            Normalized invariant
            [`PointGroupBasis`][qten.pointgroups.basis.PointGroupBasis]
            labels spanning the image of the trivial projector.
        """

        projector = self.trivial_projector(order)
        euclidean_basis = self.generators[0].euclidean_basis(order)
        labels: list[PointGroupBasis] = []
        seen: set[tuple[sy.Expr, ...]] = set()
        for vec in projector.columnspace():
            rep = sy.ImmutableDenseMatrix(vec)
            if all(entry == 0 for entry in rep):
                continue
            basis = PointGroupBasis.from_rep(
                rep=rep,
                euclidean_basis=euclidean_basis,
                axes=self.axes,
                order=order,
            )
            key = tuple(basis.rep)
            if key in seen:
                continue
            seen.add(key)
            labels.append(basis)
        return tuple(labels)
