import sympy as sy
from dataclasses import dataclass
from typing import Any, Iterable
from .basis import PointGroupBasis as PointGroupBasis
from .elements import PointGroupElement as PointGroupElement

def _matrix_key(matrix: sy.ImmutableDenseMatrix) -> tuple[float, ...]: ...
@dataclass(frozen=True)
class FinitePointGroup:
    generators: tuple[PointGroupElement, ...]
    axes: tuple[sy.Symbol, ...]
    symbol: str | None
    irreps: dict[str, Any] | None
    spinor_irreps: dict[str, Any] | None
    spin: str

    @classmethod
    def from_matrices(
        cls,
        matrices: Iterable[sy.ImmutableDenseMatrix],
        axes: tuple[sy.Symbol, ...],
        *,
        symbol: str | None = None,
        irreps: dict[str, Any] | None = None,
        spinor_irreps: dict[str, Any] | None = None,
        rotation3s: Iterable[sy.ImmutableDenseMatrix | None] | None = None,
        spin: str = "electron",
    ) -> FinitePointGroup: ...
    def elements(self, max_order: int = 512) -> tuple[PointGroupElement, ...]: ...
    def order(self) -> int: ...
    def is_abelian(self) -> bool: ...
    def conjugacy_classes(self) -> tuple[tuple[int, ...], ...]: ...
    def _generated_class_indices(self) -> tuple[int, ...]: ...
    def _class_label_index_by_element(self) -> tuple[int, ...]: ...
    def ordinary_table(self) -> dict[str, Any]: ...
    def spinor_table(self) -> dict[str, Any]: ...
    def element_class_indices(self) -> tuple[int, ...]: ...
    def irrep_characters_by_element(self, irrep: str) -> tuple[sy.Expr, ...]: ...
    def spinor_irrep_characters_by_element(self, irrep: str) -> tuple[complex, ...]: ...
    def reoriented_by(self, rotation: sy.Matrix) -> FinitePointGroup: ...
    def trivial_projector(self, order: int) -> sy.ImmutableDenseMatrix: ...
    def irrep_projector(self, order: int, irrep: str) -> sy.ImmutableDenseMatrix: ...
    def irrep_basis(self, order: int, irrep: str) -> tuple[PointGroupBasis, ...]: ...
    def invariant_basis(self, order: int) -> tuple[PointGroupBasis, ...]: ...
