"""Finite point groups generated by exact symbolic matrices."""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from typing import Any, Iterable

import sympy as sy

from .elements import PointGroupElement
from .basis import PointGroupBasis


def _matrix_key(matrix: sy.ImmutableDenseMatrix) -> tuple[sy.Expr, ...]:
    return tuple(sy.simplify(entry) for entry in matrix)


def _character_expr(value: Any) -> sy.Expr:
    if isinstance(value, int):
        return sy.Integer(value)
    if isinstance(value, float):
        return sy.Rational(str(value))
    if isinstance(value, str):
        if value in ("", "·"):
            return sy.Integer(0)
        w = sy.exp(2 * sy.pi * sy.I / 3)
        text = value.replace("^", "**")
        return sy.simplify(sy.sympify(text, locals={"w": w}))
    return sy.sympify(value)


def _as_int(value: sy.Expr) -> int | None:
    simplified = sy.simplify(value)
    if simplified.is_integer:
        return int(simplified)
    return None


@dataclass(frozen=True)
class FinitePointGroup:
    """Finite point group represented by exact generator matrices."""

    generators: tuple[PointGroupElement, ...]
    axes: tuple[sy.Symbol, ...]
    symbol: str | None = None
    irreps: dict[str, Any] | None = field(default=None, compare=False, hash=False)

    def __post_init__(self) -> None:
        if not self.generators:
            raise ValueError("FinitePointGroup requires at least one generator.")
        if any(generator.axes != self.axes for generator in self.generators):
            raise ValueError("All generators must share the group's ordered axes.")
        dim = len(self.axes)
        if any(generator.irrep.shape != (dim, dim) for generator in self.generators):
            raise ValueError("Generator matrix shape must match the axis dimension.")

    @classmethod
    def from_matrices(
        cls,
        matrices: Iterable[sy.ImmutableDenseMatrix],
        axes: tuple[sy.Symbol, ...],
        *,
        symbol: str | None = None,
        irreps: dict[str, Any] | None = None,
    ) -> "FinitePointGroup":
        generators = tuple(
            PointGroupElement(irrep=matrix, axes=axes) for matrix in matrices
        )
        return cls(generators=generators, axes=axes, symbol=symbol, irreps=irreps)

    @lru_cache
    def elements(self, max_order: int = 512) -> tuple[PointGroupElement, ...]:
        """Generate all group elements by closure under the generators."""

        dim = len(self.axes)
        identity = PointGroupElement(
            irrep=sy.ImmutableDenseMatrix.eye(dim), axes=self.axes
        )
        elements = [identity]
        seen = {_matrix_key(identity.irrep)}
        frontier = [identity]

        while frontier:
            current = frontier.pop(0)
            for generator in self.generators:
                for candidate in (generator @ current, current @ generator):
                    key = _matrix_key(candidate.irrep)
                    if key in seen:
                        continue
                    seen.add(key)
                    elements.append(candidate)
                    frontier.append(candidate)
                    if len(elements) > max_order:
                        raise ValueError(
                            "Failed to close finite point group within "
                            f"max_order={max_order}."
                        )

        return tuple(elements)

    @property
    def order(self) -> int:
        """Number of generated group elements."""

        return len(self.elements())

    def is_abelian(self) -> bool:
        """Return whether all generated elements commute."""

        elements = self.elements()
        zero = sy.zeros(len(self.axes), len(self.axes))
        for i, left in enumerate(elements):
            for right in elements[i + 1 :]:
                if not sy.simplify(
                    left.irrep @ right.irrep - right.irrep @ left.irrep
                ).equals(zero):
                    return False
        return True

    @lru_cache
    def conjugacy_classes(self) -> tuple[tuple[int, ...], ...]:
        """Return conjugacy classes as element-index tuples."""

        elements = self.elements()
        key_to_index = {
            _matrix_key(element.irrep): i for i, element in enumerate(elements)
        }
        unassigned = set(range(len(elements)))
        classes: list[tuple[int, ...]] = []
        while unassigned:
            i = min(unassigned)
            representative = elements[i]
            class_indices = set()
            for h in elements:
                conjugated = h @ representative @ h.inv()
                class_indices.add(key_to_index[_matrix_key(conjugated.irrep)])
            classes.append(tuple(sorted(class_indices)))
            unassigned -= class_indices
        return tuple(classes)

    def _reflection_label_2d(self, matrix: sy.ImmutableDenseMatrix) -> str:
        """Classify common 2D crystallographic mirror classes."""

        fixed = (matrix - sy.ImmutableDenseMatrix.eye(2)).nullspace()
        if not fixed:
            return "m"
        vec = fixed[0]
        x_nonzero = sy.simplify(vec[0]) != 0
        y_nonzero = sy.simplify(vec[1]) != 0
        if x_nonzero ^ y_nonzero:
            return "m100"
        return "m1-10"

    @staticmethod
    def _label_order(label: str) -> int | None:
        text = label.lstrip("-")
        for char in text:
            if char.isdigit():
                return int(char)
        return None

    def _label_matches_class(
        self,
        *,
        label: str,
        order: int,
        det: sy.Expr,
        trace: sy.Expr,
        dim: int,
    ) -> bool:
        """Return whether a class label is compatible with matrix invariants."""

        det_int = _as_int(det)
        trace_int = _as_int(trace)

        if label == "1":
            return order == 1
        if label == "-1":
            return order == 2 and det_int == -1 and trace_int == -dim
        if label.startswith("m"):
            return order == 2 and det_int == -1 and trace_int == dim - 2
        if label.startswith("-"):
            label_order = self._label_order(label)
            if label_order is not None and order != label_order:
                return False
            return det_int == -1
        label_order = self._label_order(label)
        if label_order is not None and order != label_order:
            return False
        return det_int == 1

    @lru_cache
    def _class_label_index_by_element(self) -> tuple[int, ...]:
        """Map each generated element index to irreps.class_labels index."""

        if not self.irreps:
            raise ValueError(f"No character-table data is available for {self.symbol}.")
        labels = tuple(self.irreps["class_labels"])
        multiplicities = tuple(int(m) for m in self.irreps["multiplicities"])
        classes = self.conjugacy_classes()
        elements = self.elements()
        if len(classes) != len(labels):
            raise ValueError(
                "Character-table class count does not match generated conjugacy classes "
                f"for point group {self.symbol}."
            )

        class_info: list[dict[str, Any]] = []
        for class_index, members in enumerate(classes):
            representative = elements[members[0]]
            matrix = sy.ImmutableDenseMatrix(sy.simplify(representative.irrep))
            class_info.append(
                {
                    "class_index": class_index,
                    "size": len(members),
                    "order": representative.group_order(),
                    "det": sy.simplify(matrix.det()),
                    "trace": sy.simplify(matrix.trace()),
                    "dim": matrix.rows,
                }
            )

        slot_candidates: dict[int, list[int]] = {}
        for info in class_info:
            size = info["size"]
            size_matches = [
                i for i, multiplicity in enumerate(multiplicities) if multiplicity == size
            ]
            if not size_matches:
                raise ValueError(
                    "Could not align generated conjugacy class sizes to character-table "
                    f"multiplicities for point group {self.symbol}."
                )
            strong_matches = [
                i
                for i in size_matches
                if self._label_matches_class(
                    label=labels[i],
                    order=info["order"],
                    det=info["det"],
                    trace=info["trace"],
                    dim=info["dim"],
                )
            ]
            slot_candidates[info["class_index"]] = strong_matches or size_matches

        ordered_classes = sorted(slot_candidates, key=lambda idx: len(slot_candidates[idx]))
        assignment: dict[int, int] = {}
        used_slots: set[int] = set()

        def _search(pos: int) -> bool:
            if pos == len(ordered_classes):
                return True
            class_index = ordered_classes[pos]
            for slot_index in slot_candidates[class_index]:
                if slot_index in used_slots:
                    continue
                assignment[class_index] = slot_index
                used_slots.add(slot_index)
                if _search(pos + 1):
                    return True
                used_slots.remove(slot_index)
                del assignment[class_index]
            return False

        if not _search(0):
            raise ValueError(
                "Failed to align generated conjugacy classes with character-table labels "
                f"for point group {self.symbol}."
            )

        class_by_element = [0] * len(elements)
        for class_index, member_indices in enumerate(classes):
            slot_index = assignment[class_index]
            for element_index in member_indices:
                class_by_element[element_index] = slot_index
        return tuple(class_by_element)

    def element_class_indices(self) -> tuple[int, ...]:
        """Return the aligned character-table class index for each element index."""

        return self._class_label_index_by_element()

    def irrep_characters_by_element(self, irrep: str) -> tuple[sy.Expr, ...]:
        """Return irrep characters ordered by generated group elements."""

        if not self.irreps:
            raise ValueError(f"No character-table data is available for {self.symbol}.")
        irrep_table = self.irreps["irreps"]
        if irrep not in irrep_table:
            raise ValueError(f"Unknown irrep '{irrep}' for point group {self.symbol}.")

        labels = self.irreps["class_labels"]
        characters = tuple(
            _character_expr(character) for character in irrep_table[irrep]["characters"]
        )
        if len(characters) != len(labels):
            raise ValueError(
                f"Character row length for irrep '{irrep}' does not match class labels."
            )

        class_by_element = self._class_label_index_by_element()
        return tuple(characters[class_index] for class_index in class_by_element)

    @lru_cache
    def trivial_projector(self, order: int) -> sy.ImmutableDenseMatrix:
        """Project the polynomial representation onto the invariant sector."""

        reps = [element.euclidean_repr(order) for element in self.elements()]
        projector = sy.zeros(reps[0].rows, reps[0].cols)
        for rep in reps:
            projector += rep
        return sy.ImmutableDenseMatrix(sy.simplify(projector / len(reps)))

    @lru_cache
    def irrep_projector(self, order: int, irrep: str) -> sy.ImmutableDenseMatrix:
        """Project the polynomial representation onto a character-table sector."""

        if not self.irreps:
            raise ValueError(f"No character-table data is available for {self.symbol}.")
        irrep_table = self.irreps["irreps"]
        if irrep not in irrep_table:
            raise ValueError(f"Unknown irrep '{irrep}' for point group {self.symbol}.")

        labels = self.irreps["class_labels"]
        row = irrep_table[irrep]
        characters = tuple(_character_expr(character) for character in row["characters"])
        if len(characters) != len(labels):
            raise ValueError(
                f"Character row length for irrep '{irrep}' does not match class labels."
            )

        elements = self.elements()
        class_by_element = self._class_label_index_by_element()
        reps = [element.euclidean_repr(order) for element in elements]
        projector = sy.zeros(reps[0].rows, reps[0].cols)
        for element_index, rep in enumerate(reps):
            class_index = class_by_element[element_index]
            projector += sy.conjugate(characters[class_index]) * rep

        dim = sy.Integer(row["dim"])
        return sy.ImmutableDenseMatrix(sy.simplify((dim / len(elements)) * projector))

    @lru_cache
    def irrep_basis(self, order: int, irrep: str) -> tuple[PointGroupBasis, ...]:
        """Return polynomial basis labels spanning a finite point-group irrep sector."""

        if not self.irreps:
            raise ValueError(f"No character-table data is available for {self.symbol}.")
        irrep_data = self.irreps["irreps"][irrep]
        irrep_dim = int(irrep_data["dim"])
        projector = self.irrep_projector(order, irrep)
        euclidean_basis = self.generators[0].euclidean_basis(order)
        labels: list[PointGroupBasis] = []
        seen: set[tuple[sy.Expr, ...]] = set()
        for vec in projector.columnspace():
            rep = sy.ImmutableDenseMatrix(vec)
            if all(entry == 0 for entry in rep):
                continue
            basis = PointGroupBasis.from_rep(
                rep=rep,
                euclidean_basis=euclidean_basis,
                axes=self.axes,
                order=order,
                group=self.symbol or "<anonymous>",
                irrep=irrep,
                irrep_dim=irrep_dim,
                copy_index=len(labels) // max(irrep_dim, 1),
                component_index=len(labels) % max(irrep_dim, 1),
            )
            key = tuple(basis.rep)
            if key in seen:
                continue
            seen.add(key)
            labels.append(basis)
        return tuple(labels)

    @lru_cache
    def invariant_basis(self, order: int) -> tuple[PointGroupBasis, ...]:
        """Return invariant polynomial basis functions of the requested degree."""

        projector = self.trivial_projector(order)
        euclidean_basis = self.generators[0].euclidean_basis(order)
        labels: list[PointGroupBasis] = []
        seen: set[tuple[sy.Expr, ...]] = set()
        for vec in projector.columnspace():
            rep = sy.ImmutableDenseMatrix(vec)
            if all(entry == 0 for entry in rep):
                continue
            basis = PointGroupBasis.from_rep(
                rep=rep,
                euclidean_basis=euclidean_basis,
                axes=self.axes,
                order=order,
            )
            key = tuple(basis.rep)
            if key in seen:
                continue
            seen.add(key)
            labels.append(basis)
        return tuple(labels)
