import abc
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Callable, Generic, Self, TypeVar
from typing_extensions import final

@dataclass(frozen=True)
class Operable(ABC):
    def __add__(self, other): ...
    def __neg__(self): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    def __matmul__(self, other): ...
    def __truediv__(self, other): ...
    def __floordiv__(self, other): ...
    def __pow__(self, other): ...
    def __eq__(self, value): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __and__(self, other): ...
    def __or__(self, other): ...
    def __radd__(self, other): ...
    def __rsub__(self, other): ...
    def __rmul__(self, other): ...
    def __rtruediv__(self, other): ...

UpdatableType = TypeVar("UpdatableType", bound="Updatable")
_InnerProductType = TypeVar("_InnerProductType")
_ElementType = TypeVar("_ElementType")

class Updatable(ABC, Generic[UpdatableType], metaclass=abc.ABCMeta):
    def update(self, **kwargs) -> UpdatableType: ...

class HasDual(ABC, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def dual(self): ...

BaseType = TypeVar("BaseType")

class HasBase(ABC, Generic[BaseType], metaclass=abc.ABCMeta):
    @abstractmethod
    def base(self) -> BaseType: ...
    @abstractmethod
    def rebase(self, new_base: BaseType) -> HasBase[BaseType]: ...

class AbstractKet(ABC, Generic[_InnerProductType], metaclass=abc.ABCMeta):
    @abstractmethod
    def ket(self, another: Self) -> _InnerProductType: ...

class Functional(ABC):
    @classmethod
    def register(cls, obj_type: type): ...
    @staticmethod
    def get_applicable_types(cls) -> tuple[type, ...]: ...
    def allows(self, obj: Any) -> bool: ...
    def invoke(self, obj: Any, **kwargs) -> Any: ...
    def __call__(self, obj: Any, **kwargs) -> Any: ...

class Span(ABC, Generic[_ElementType], metaclass=abc.ABCMeta):
    @abstractmethod
    def elements(self) -> tuple[_ElementType, ...]: ...
    def contains(self, v) -> bool: ...

class HasRays(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def rays(self) -> Self: ...

A = TypeVar("A", bound="Convertible")
B = TypeVar("B")

class Convertible(ABC):
    @classmethod
    def add_conversion(
        cls, T: type[B]
    ) -> Callable[[Callable[[A], B]], Callable[[A], B]]: ...
    @final
    def convert(self, T: type[B]) -> B: ...
