import torch
from ..abstracts import Convertible as Convertible, Operable as Operable
from ..plottings import Plottable as Plottable
from ..precision import get_precision_config as get_precision_config
from ..symbolics.state_space import (
    BroadcastSpace as BroadcastSpace,
    IndexSpace as IndexSpace,
    StateSpace as StateSpace,
    StateSpaceFactorization as StateSpaceFactorization,
    embedding_order as embedding_order,
    permutation_order as permutation_order,
    same_rays as same_rays,
)
from ..utils.devices import Device as Device, DeviceBounded as DeviceBounded
from ..validations import need_validation as need_validation
from _typeshed import Incomplete
from dataclasses import dataclass
from types import EllipsisType
from typing import (
    Any,
    Callable,
    Generic,
    NamedTuple,
    overload,
    Self,
    Sequence,
    TypeAlias,
    TypeVar,
)
from typing_extensions import override

T = TypeVar("T", bound=torch.Tensor)
TensorType = TypeVar("TensorType", bound="Tensor[Any]")
Scalar: TypeAlias = int | float | complex

@dataclass(frozen=True, eq=False)
class Tensor(Operable, Plottable, Convertible, DeviceBounded, Generic[T]):
    data: T
    dims: tuple[StateSpace, ...]
    @staticmethod
    def scalar(number: Scalar) -> Tensor: ...
    def astype(self, dtype: torch.dtype) -> Self: ...
    def equal(self, other: Tensor) -> bool: ...
    def allclose(
        self,
        other: Tensor,
        rtol: float = 1e-05,
        atol: float = 1e-08,
        equal_nan: bool = False,
    ) -> bool: ...
    def isclose(
        self,
        other: Tensor | Scalar,
        rtol: float = 1e-05,
        atol: float = 1e-08,
        equal_nan: bool = False,
    ) -> Self: ...
    def conj(self) -> Self: ...
    def real(self) -> Self: ...
    def imag(self) -> Self: ...
    def abs(self) -> Self: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    @overload
    def __add__(self, other: Tensor) -> Tensor: ...
    @overload
    def __add__(self, other: Scalar) -> Tensor: ...
    def __radd__(self, other: Scalar) -> Tensor: ...
    def __eq__(self: TensorType, other: Tensor) -> TensorType: ...  # type: ignore[override]
    def __lt__(self: TensorType, other: Tensor) -> TensorType: ...
    def __le__(self: TensorType, other: Tensor) -> TensorType: ...
    def __gt__(self: TensorType, other: Tensor) -> TensorType: ...
    def __ge__(self: TensorType, other: Tensor) -> TensorType: ...
    def __neg__(self: TensorType) -> TensorType: ...
    @overload
    def __sub__(self, other: Tensor) -> Tensor: ...
    @overload
    def __sub__(self, other: Scalar) -> Tensor: ...
    def __rsub__(self, other: Scalar) -> Tensor: ...
    def __mul__(self, other: Scalar) -> Tensor: ...
    def __rmul__(self, other: Scalar) -> Tensor: ...
    def __truediv__(self, other: Scalar) -> Tensor: ...
    def permute(self, *order: int | Sequence[int]) -> Self: ...
    def transpose(self, dim0: int, dim1: int) -> Self: ...
    def h(self, dim0: int, dim1: int) -> Self: ...
    def align(self, dim: int, target_dim: StateSpace) -> Self: ...
    def align_all(self, dims: tuple[StateSpace, ...]) -> Self: ...
    def all(
        self, dim: int | tuple[int, ...] | None = None, keepdim: bool = False
    ) -> Self: ...
    @overload
    def where(
        self,
        input: Tensor,
        other: Tensor,
        index_type: type[Any] = ...,
    ) -> Tensor: ...
    @overload
    def where(
        self,
        input: None = None,
        other: None = None,
        index_type: type["Tensor[Any]"] = ...,
    ) -> tuple["Tensor", ...]: ...
    @overload
    def where(
        self,
        input: None = None,
        other: None = None,
        index_type: type[tuple] = tuple,
    ) -> tuple[tuple[int, ...], ...]: ...
    @overload
    def where(
        self,
        input: None = None,
        other: None = None,
        index_type: type[StateSpace[Any]] = StateSpace,
    ) -> StateSpace[Any]: ...
    @overload
    def where(
        self,
        input: Tensor | None = None,
        other: Tensor | None = None,
        index_type: type[Any] = ...,
    ) -> (
        Tensor | tuple["Tensor", ...] | tuple[tuple[int, ...], ...] | StateSpace[Any]
    ): ...
    @overload
    def nonzero(
        self, as_tuple: bool = True, index_type: type["Tensor[Any]"] = ...
    ) -> tuple["Tensor", ...]: ...
    @overload
    def nonzero(
        self, as_tuple: bool = True, index_type: type[tuple] = tuple
    ) -> tuple[tuple[int, ...], ...]: ...
    @overload
    def nonzero(
        self, as_tuple: bool = True, index_type: type[StateSpace[Any]] = StateSpace
    ) -> StateSpace[Any]: ...
    @overload
    def nonzero(
        self, as_tuple: bool = True, index_type: type[Any] = ...
    ) -> tuple["Tensor", ...] | tuple[tuple[int, ...], ...] | StateSpace[Any]: ...
    def unsqueeze(self, dim: int) -> Self: ...
    def squeeze(self, dim: int) -> Self: ...
    def rank(self) -> int: ...
    def mean(self, dim: int | tuple[int, ...] | None = None) -> Self: ...
    def argmax(self, dim: int) -> Self: ...
    def argmin(self, dim: int) -> Self: ...
    def expand_to_union(self, union_dims: list[StateSpace]) -> Self: ...
    def item(self) -> Scalar: ...
    @override
    @property
    def device(self) -> Device: ...
    @override
    def to_device(self, device: Device) -> Self: ...
    @property
    def requires_grad(self) -> bool: ...
    @property
    def grad(self) -> Self | None: ...
    def backward(
        self,
        gradient: Self | None = None,
        retain_graph: bool | None = None,
        create_graph: bool = False,
        inputs: Sequence[Self] | None = None,
    ) -> None: ...
    def attach(self) -> Self: ...
    def detach(self) -> Self: ...
    def clone(self) -> Self: ...
    def replace_dim(self, dim: int, new_dim: StateSpace) -> Self: ...
    def __getitem__(self, key): ...
    def factorize_dim(self, dim: int, rule: StateSpaceFactorization) -> Self: ...
    def product_dims(self, *indices_group: tuple[int, ...]) -> Self: ...
    def dim_types(self) -> tuple[type, ...]: ...

def auto_promote(func): ...
@auto_promote
def matmul(left: Tensor, right: Tensor) -> Tensor: ...
def permute(tensor: TensorType, *order: int | Sequence[int]) -> TensorType: ...
def transpose(tensor: TensorType, dim0: int, dim1: int) -> TensorType: ...
def conj(tensor: TensorType) -> TensorType: ...
def real(tensor: TensorType) -> TensorType: ...
def imag(tensor: TensorType) -> TensorType: ...
def abs(tensor: TensorType) -> TensorType: ...
def unsqueeze(tensor: TensorType, dim: int) -> TensorType: ...
def squeeze(tensor: TensorType, dim: int) -> TensorType: ...
def align(tensor: TensorType, dim: int, target_dim: StateSpace) -> TensorType: ...
def align_all(tensor: TensorType, dims: tuple[StateSpace, ...]) -> TensorType: ...
def all(
    tensor: TensorType, dim: int | tuple[int, ...] | None = None, keepdim: bool = False
) -> TensorType: ...
def rank(tensor: Tensor) -> int: ...
def mean(
    tensor: TensorType, dim: int | tuple[int, ...] | None = None
) -> TensorType: ...
def argmax(tensor: TensorType, dim: int) -> TensorType: ...
def argmin(tensor: TensorType, dim: int) -> TensorType: ...
def one_hot(
    tensor: Tensor[torch.LongTensor], dim: StateSpace
) -> Tensor[torch.LongTensor]: ...
def astype(tensor: TensorType, dtype: torch.dtype) -> TensorType: ...
def allclose(
    a: Tensor,
    b: Tensor,
    rtol: float = 1e-05,
    atol: float = 1e-08,
    equal_nan: bool = False,
) -> bool: ...
def isclose(
    a: TensorType,
    b: Tensor | Scalar,
    rtol: float = 1e-05,
    atol: float = 1e-08,
    equal_nan: bool = False,
) -> TensorType: ...
def equal(a: Tensor, b: Tensor) -> bool: ...
def expand_to_union(tensor: TensorType, union_dims: list[StateSpace]) -> TensorType: ...
def union_dims(
    *dims: tuple[StateSpace, ...], allow_merge: bool = False
) -> tuple[StateSpace, ...]: ...
def mapping_matrix(
    from_space: StateSpace,
    to_space: StateSpace,
    mapping: dict[Any, Any],
    factors: dict[tuple[Any, Any], int | float | complex] | None = None,
) -> Tensor: ...
def eye(dims: tuple[StateSpace, ...]) -> Tensor: ...
def zeros(dims: tuple[StateSpace, ...]) -> Tensor: ...
def ones(dims: tuple[StateSpace, ...]) -> Tensor: ...
def kernel_tensor(
    ker: Callable[..., Scalar], dims: tuple[StateSpace, ...]
) -> Tensor[torch.Tensor]: ...
def replace_dim(tensor: TensorType, dim: int, new_dim: StateSpace) -> TensorType: ...
def factorize_dim(
    tensor: TensorType, dim: int, rule: StateSpaceFactorization
) -> TensorType: ...
def product_dims(tensor: TensorType, *indices_group: tuple[int, ...]) -> TensorType: ...
def promote_rank(tensor: Tensor, target_rank: int) -> Tensor: ...
@overload
def nonzero(
    condition: Tensor, as_tuple: bool = True, index_type: type[Tensor[Any]] = ...
) -> tuple[Tensor, ...]: ...
@overload
def nonzero(
    condition: Tensor, as_tuple: bool = True, index_type: type[tuple] = tuple
) -> tuple[tuple[int, ...], ...]: ...
@overload
def nonzero(
    condition: Tensor,
    as_tuple: bool = True,
    index_type: type[StateSpace[Any]] = StateSpace,
) -> StateSpace[Any]: ...
@overload
def nonzero(
    condition: Tensor, as_tuple: bool = True, index_type: type[Any] = ...
) -> tuple[Tensor, ...] | tuple[tuple[int, ...], ...] | StateSpace[Any]: ...
@overload
def where(
    condition: Tensor[torch.BoolTensor], input: Tensor, other: Tensor
) -> Tensor: ...
@overload
def where(
    condition: Tensor[torch.BoolTensor], index_type: type[Tensor[Any]] = ...
) -> tuple[Tensor, ...]: ...
@overload
def where(
    condition: Tensor[torch.BoolTensor], index_type: type[tuple] = tuple
) -> tuple[tuple[int, ...], ...]: ...
@overload
def where(
    condition: Tensor[torch.BoolTensor], index_type: type[StateSpace[Any]] = StateSpace
) -> StateSpace[Any]: ...
@overload
def where(
    condition: Tensor[torch.BoolTensor], index_type: type[Any] = ...
) -> tuple[Tensor, ...] | tuple[tuple[int, ...], ...] | StateSpace[Any]: ...

TensorIndexType: TypeAlias = (
    int | slice | EllipsisType | None | Convertible | StateSpace | Tensor
)
TorchIndexType: TypeAlias = Any

class TensorIndexing:
    dims: Incomplete
    rank: Incomplete
    indices: Incomplete
    non_none_indices: Incomplete
    tensor_union_dims: Incomplete
    def __init__(
        self, dims: tuple[StateSpace, ...], indices: tuple[TensorIndexType, ...]
    ) -> None: ...
    class CompiledIndices(NamedTuple):
        indices: tuple[TorchIndexType, ...]
        dims: tuple[StateSpace, ...]
        indices_steps: tuple[int | slice | None | tuple[int, ...], ...]
        has_tensor_index: bool

    def compile(self) -> CompiledIndices: ...
