from __future__ import annotations

from abc import ABC
from collections import OrderedDict
from collections.abc import Iterable, Iterator
from typing import (
    Any,
    Callable,
    Dict,
    Generic,
    Optional,
    Tuple,
    Type,
    TypeVar,
    Union,
    overload,
)

import sympy as sy

from .abstracts import (
    AbstractKet,
    Convertible,
    Functional,
    HasRays,
    Operable,
    Span,
)
from .spatials import Spatial
from .state_space import StateSpace, StateSpaceFactorization
from .symbolics import Multiple
from .tensors import Tensor
from .utils import FrozenDict

_IrrepType = TypeVar("_IrrepType")
_ValueType = TypeVar("_ValueType")
_OperableType = TypeVar("_OperableType", bound=Operable)

class U1Basis(
    Spatial, Multiple[Tuple[Any, ...]], AbstractKet[sy.Expr], HasRays, Convertible
):
    coef: sy.Number
    base: Tuple[Any, ...]
    rep: Tuple[Any, ...]
    def __init__(self, coef: sy.Number, base: Tuple[Any, ...]) -> None: ...
    def __post_init__(self) -> None: ...
    @staticmethod
    def new(*rep: Any) -> U1Basis: ...
    @property
    def dim(self) -> int: ...
    def replace(self, irrep: Any) -> U1Basis: ...
    def irrep_of(self, T: Type[_IrrepType]) -> _IrrepType: ...
    def ket(self, psi: U1Basis) -> sy.Expr: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def rays(self) -> U1Basis: ...
    def repr_types(self) -> Tuple[Type[Any], ...]: ...
    def __lt__(self, other: U1Basis) -> bool: ...
    def __gt__(self, other: U1Basis) -> bool: ...
    def __matmul__(self, other: U1Basis) -> U1Basis: ...
    @overload
    def __or__(self, other: U1Basis) -> U1Span: ...
    @overload
    def __or__(self, other: U1Span) -> U1Span: ...
    @overload
    def __or__(self, other: HilbertSpace) -> HilbertSpace: ...
    def __eq__(self, value: object) -> bool: ...

class U1Span(Span[U1Basis], Spatial, HasRays, Convertible):
    span: Tuple[U1Basis, ...]
    def __init__(self, span: Tuple[U1Basis, ...]) -> None: ...
    @property
    def dim(self) -> int: ...
    def __iter__(self) -> Iterator[U1Basis]: ...
    def elements(self) -> Tuple[U1Basis, ...]: ...
    def rays(self) -> U1Span: ...
    def cross_gram(self, ket: U1Span) -> sy.ImmutableDenseMatrix: ...
    @overload
    def __or__(self, other: U1Basis) -> U1Span: ...
    @overload
    def __or__(self, other: U1Span) -> U1Span: ...
    def __sub__(self, other: U1Span) -> U1Span: ...
    def __and__(self, other: U1Span) -> U1Span: ...

class HilbertSpace(HasRays, StateSpace[U1Basis], Span[U1Basis]):
    structure: OrderedDict[U1Basis, int]
    def __init__(self, structure: OrderedDict[U1Basis, int]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def lookup(self, query: Dict[Type[Any], Any]) -> U1Basis: ...
    def elements(self) -> Tuple[U1Basis, ...]: ...
    def group(
        self, **groups: Union[Callable[[U1Basis], bool], Any]
    ) -> FrozenDict[str, HilbertSpace]: ...
    def group_by(self, *T: Type[Any]) -> Tuple[HilbertSpace, ...]: ...
    def is_homogeneous(self) -> bool: ...
    def canonical_basis_types(self) -> Tuple[Type[Any], ...]: ...
    def factorize(
        self, *irrep_types: Tuple[Type[Any], ...], coef_on: Optional[int] = ...
    ) -> StateSpaceFactorization: ...
    def tensor_product(self, other: HilbertSpace) -> HilbertSpace: ...
    def rays(self) -> HilbertSpace: ...
    def cross_gram(self, another: HilbertSpace) -> Tensor: ...
    @overload
    def __or__(self, other: U1Basis) -> HilbertSpace: ...
    @overload
    def __or__(self, other: HilbertSpace) -> HilbertSpace: ...
    def __sub__(self, other: HilbertSpace) -> HilbertSpace: ...
    def __and__(self, other: HilbertSpace) -> HilbertSpace: ...

def hilbert(itr: Iterable[U1Basis]) -> HilbertSpace: ...
def u1basis_to_u1span(basis: U1Basis) -> U1Span: ...
def u1basis_to_hilbertspace(basis: U1Basis) -> HilbertSpace: ...
def u1span_to_hilbertspace(span: U1Span) -> HilbertSpace: ...
def hilbertspace_to_hilbertspace(v: HilbertSpace) -> HilbertSpace: ...
@overload
def same_rays(a: HilbertSpace, b: HilbertSpace) -> bool: ...
@overload
def same_rays(a: U1Basis, b: U1Basis) -> bool: ...
@overload
def same_rays(a: U1Span, b: U1Span) -> bool: ...

class U1Operator(Functional, Operable, ABC):
    def invoke(self, obj: Any, **kwargs: Any) -> Any: ...
    def __matmul__(
        self, other: _OperableType
    ) -> Union[_OperableType, Multiple[_OperableType]]: ...

class FuncOpr(Generic[_IrrepType], U1Operator):
    T: Type[_IrrepType]
    func: Callable[..., Any]
    def __init__(self, T: Type[_IrrepType], func: Callable[..., Any]) -> None: ...

def operator_lt(a: U1Basis, b: U1Basis) -> bool: ...
def operator_gt(a: U1Basis, b: U1Basis) -> bool: ...
def operator_eq(a: U1Basis, b: U1Basis) -> bool: ...
@overload
def operator_matmul(
    o: U1Operator, v: _OperableType
) -> Union[_OperableType, Multiple[_OperableType]]: ...
@overload
def operator_matmul(a: U1Basis, b: U1Basis) -> U1Basis: ...
@overload
def operator_or(a: U1Basis, b: U1Basis) -> U1Span: ...
@overload
def operator_or(span: U1Span, state: U1Basis) -> U1Span: ...
@overload
def operator_or(state: U1Basis, span: U1Span) -> U1Span: ...
@overload
def operator_or(a: U1Span, b: U1Span) -> U1Span: ...
@overload
def operator_or(space: HilbertSpace, state: U1Basis) -> HilbertSpace: ...
@overload
def operator_or(state: U1Basis, space: HilbertSpace) -> HilbertSpace: ...
def operator_sub(a: U1Span, b: U1Span) -> U1Span: ...
def operator_and(a: U1Span, b: U1Span) -> U1Span: ...
